/* ==========================================================================
   decoder.js — the German you meet on TikTok, in comments and in voice notes
   `risk`: ok = say it anywhere · mid = friends only · risk = don't say it,
   just understand it.
   ========================================================================== */
(function () {
  'use strict';
  window.DE.decoder = {
    groups: ['Slang', 'Reaktion', 'Kommentare', 'Gesprochen', 'Füllwörter', 'Neu 2026'],
    items: [
      /* ------------------------------------------------------- Slang --- */
      { de: 'Digga', en: 'dude, bro — the single most common piece of German slang', lit: 'from "Dicker" (fat one), Hamburg hip-hop',
        use: 'Digga, was machst du?', useEn: 'Dude, what are you doing?', group: 'Slang', risk: 'mid' },
      { de: 'Alter', en: 'man / dude — same job as Digga, slightly older-feeling', lit: 'old one',
        use: 'Alter, das ist doch nicht dein Ernst.', useEn: "Dude, you can't be serious.", group: 'Slang', risk: 'mid' },
      { de: 'krass', en: 'insane, wild, intense — good or bad, tone decides', lit: 'crass',
        use: 'Das ist echt krass.', useEn: "That's actually insane.", group: 'Slang', risk: 'ok' },
      { de: 'geil', en: 'awesome, sick. Everyday word despite its literal meaning', lit: 'horny (literally) — nobody hears it that way here',
        use: 'Das Video ist so geil.', useEn: 'That video is so good.', group: 'Slang', risk: 'mid' },
      { de: 'Bock haben', en: 'to be up for something, to feel like it', lit: 'to have a billy goat',
        use: 'Hast du Bock auf Kino?', useEn: 'You up for the cinema?', group: 'Slang', risk: 'ok' },
      { de: 'keine Ahnung', en: 'no idea / dunno. Often shortened to "ka"', lit: 'no notion',
        use: 'Keine Ahnung, ehrlich.', useEn: 'No idea, honestly.', group: 'Slang', risk: 'ok' },
      { de: 'läuft bei dir', en: "things are going well for you — half praise, half tease", lit: 'it runs at you',
        use: 'Neues Auto? Läuft bei dir!', useEn: 'New car? Look at you!', group: 'Slang', risk: 'ok' },
      { de: 'Was geht?', en: "what's up?", lit: 'what goes',
        use: 'Ey, was geht?', useEn: 'Hey, what’s up?', group: 'Slang', risk: 'ok' },
      { de: 'Was geht ab?', en: "what's going on / what's up (stronger)", lit: 'what goes off',
        use: 'Was geht ab, Leute?', useEn: "What's up, everyone?", group: 'Slang', risk: 'ok' },
      { de: 'Hab ich nicht mit gerechnet', en: "didn't see that coming", lit: 'I did not count with that',
        use: 'Ende: hab ich nicht mit gerechnet.', useEn: "That ending — did not see it coming.", group: 'Slang', risk: 'ok' },
      { de: 'Macker', en: 'boyfriend, crush, or just "guy"', lit: 'bloke',
        use: 'Ist das dein Macker?', useEn: 'Is that your guy?', group: 'Neu 2026', risk: 'mid' },
      { de: 'Talahon', en: 'stereotype of a swaggering young man in a tracksuit; heavily meme-ified', lit: 'from Arabic "ta\'āl hōn" = come here',
        use: 'Der läuft wie ein Talahon.', useEn: 'He walks like a Talahon.', group: 'Slang', risk: 'risk' },
      { de: 'Ehrenmann / Ehrenfrau', en: 'someone who did a genuinely decent thing', lit: 'man/woman of honour',
        use: 'Du hast bezahlt? Ehrenmann.', useEn: 'You paid? Absolute legend.', group: 'Slang', risk: 'ok' },
      { de: 'Wallah', en: 'I swear — extremely common among young people', lit: 'Arabic: by God',
        use: 'Wallah, ich war da.', useEn: 'I swear, I was there.', group: 'Slang', risk: 'mid' },
      { de: 'Gönn dir', en: 'treat yourself, go for it', lit: 'grant yourself',
        use: 'Zweites Stück Kuchen? Gönn dir.', useEn: 'Second slice? Treat yourself.', group: 'Slang', risk: 'ok' },
      { de: 'abgehen', en: 'to go off, to be wild (party, song, video)', lit: 'to go off',
        use: 'Der Song geht ab.', useEn: 'That song goes hard.', group: 'Slang', risk: 'ok' },
      { de: 'Es ist mir Latte', en: "I couldn't care less", lit: 'it is a stick to me',
        use: 'Das ist mir echt Latte.', useEn: "I genuinely don't care.", group: 'Slang', risk: 'mid' },

      /* ------------------------------------------------- Neu / 2026 --- */
      { de: '6-7 („six seven“)', en: 'meme noise with no meaning, used to annoy adults', lit: 'a number from a song',
        use: 'Wie viel? — Sechs… sieben.', useEn: 'How much? — Six… seven.', group: 'Neu 2026', risk: 'ok', say: 'sechs sieben' },
      { de: 'Crashout', en: 'an emotional meltdown; to lose it completely', lit: 'English loanword',
        use: 'Ich hab gestern einen Crashout gehabt.', useEn: 'I had a total meltdown yesterday.', group: 'Neu 2026', risk: 'ok' },
      { de: 'Peak', en: 'the best, top tier', lit: 'English loanword',
        use: 'Das Essen war Peak.', useEn: 'The food was top tier.', group: 'Neu 2026', risk: 'ok' },
      { de: 'Ragebait', en: 'content posted purely to make you angry', lit: 'English loanword',
        use: 'Das ist doch nur Ragebait.', useEn: "That's just ragebait.", group: 'Neu 2026', risk: 'ok' },
      { de: 'Gute Käse', en: 'nonsense phrase meaning "solid / very good"', lit: 'good cheese',
        use: 'Der Schnitt? Gute Käse.', useEn: 'That edit? Solid.', group: 'Neu 2026', risk: 'ok' },
      { de: 'Süper', en: 'super — Turkish spelling, used playfully', lit: 'Turkish "süper"',
        use: 'Süper gemacht!', useEn: 'Nicely done!', group: 'Neu 2026', risk: 'ok' },
      { de: 'Du bist gut genug', en: 'ironic reassurance, from a viral track', lit: 'you are good enough',
        use: 'Du bist gut genug, Digga.', useEn: "You're good enough, man.", group: 'Neu 2026', risk: 'ok' },
      { de: 'cringe', en: 'cringe — fully naturalised into German', lit: 'English loanword',
        use: 'Das war so cringe.', useEn: 'That was so cringe.', group: 'Neu 2026', risk: 'ok' },
      { de: 'sus', en: 'suspicious, sketchy', lit: 'English loanword',
        use: 'Der Typ ist sus.', useEn: "That guy's sketchy.", group: 'Neu 2026', risk: 'ok' },
      { de: 'Sheesh', en: 'wow / damn (admiring)', lit: 'English loanword',
        use: 'Sheesh, der Beat!', useEn: 'Damn, that beat!', group: 'Neu 2026', risk: 'ok' },

      /* --------------------------------------------------- Reaktion --- */
      { de: 'Isso', en: 'exactly / facts', lit: '"ist so" = it is so',
        use: 'Isso. Genau das.', useEn: 'Facts. Exactly that.', group: 'Reaktion', risk: 'ok' },
      { de: 'Voll', en: 'totally', lit: 'full',
        use: 'Voll mein Humor.', useEn: 'Exactly my humour.', group: 'Reaktion', risk: 'ok' },
      { de: 'Genau', en: 'exactly — Germans say this constantly', lit: 'exactly',
        use: 'Genau, so meinte ich das.', useEn: "Exactly, that's what I meant.", group: 'Reaktion', risk: 'ok' },
      { de: 'Echt jetzt?', en: 'seriously? for real?', lit: 'real now',
        use: 'Echt jetzt? Das glaub ich nicht.', useEn: "Seriously? I don't believe it.", group: 'Reaktion', risk: 'ok' },
      { de: 'Ach komm', en: 'oh come on', lit: 'oh come',
        use: 'Ach komm, das stimmt doch nicht.', useEn: "Oh come on, that's not true.", group: 'Reaktion', risk: 'ok' },
      { de: 'Boah', en: 'wow / ugh — pure emotion, tone decides which', lit: '—',
        use: 'Boah, ist das schön.', useEn: 'Wow, that is beautiful.', group: 'Reaktion', risk: 'ok' },
      { de: 'Na ja…', en: 'well… (reluctant, unconvinced)', lit: 'well yes',
        use: 'Na ja, geht so.', useEn: "Well… it's alright.", group: 'Reaktion', risk: 'ok' },
      { de: 'Passt', en: "fine / works for me", lit: 'it fits',
        use: 'Um acht? — Passt.', useEn: 'Eight? — Works.', group: 'Reaktion', risk: 'ok' },
      { de: 'Alles klar', en: "got it / all good — also a greeting question", lit: 'everything clear',
        use: 'Alles klar bei dir?', useEn: 'You doing alright?', group: 'Reaktion', risk: 'ok' },
      { de: 'Bin raus', en: "I'm out, I'm done with this", lit: 'am out',
        use: 'Bei dem Preis bin ich raus.', useEn: "At that price I'm out.", group: 'Reaktion', risk: 'ok' },
      { de: 'Nice', en: 'nice — said in German constantly, pronounced English', lit: 'English loanword',
        use: 'Nice, danke dir!', useEn: 'Nice, thanks!', group: 'Reaktion', risk: 'ok' },

      /* ------------------------------------------------- Kommentare --- */
      { de: 'ka', en: 'dunno', lit: 'keine Ahnung', use: 'ka, war nicht dabei', useEn: "dunno, wasn't there", group: 'Kommentare', risk: 'ok', say: 'keine Ahnung' },
      { de: 'kp', en: 'no clue', lit: 'kein Plan', use: 'kp wie das geht', useEn: 'no clue how that works', group: 'Kommentare', risk: 'ok', say: 'kein Plan' },
      { de: 'hdl', en: 'love you (friendly, slightly childish now)', lit: 'hab dich lieb', use: 'bis morgen, hdl', useEn: 'see you tomorrow, love ya', group: 'Kommentare', risk: 'ok', say: 'hab dich lieb' },
      { de: 'hdf', en: 'shut up — rude', lit: 'halt die Fresse', use: 'hdf, keiner hat gefragt', useEn: 'shut up, nobody asked', group: 'Kommentare', risk: 'risk', say: 'halt die Fresse' },
      { de: 'wsh', en: 'wallah / I swear', lit: 'wallah', use: 'wsh war so', useEn: 'swear it was like that', group: 'Kommentare', risk: 'mid', say: 'wallah' },
      { de: 'mMn', en: 'in my opinion', lit: 'meiner Meinung nach', use: 'mMn überbewertet', useEn: 'overrated imo', group: 'Kommentare', risk: 'ok', say: 'meiner Meinung nach' },
      { de: 'vllt', en: 'maybe', lit: 'vielleicht', use: 'vllt später', useEn: 'maybe later', group: 'Kommentare', risk: 'ok', say: 'vielleicht' },
      { de: 'iwie / iwas', en: 'somehow / something', lit: 'irgendwie / irgendwas', use: 'iwie komisch', useEn: 'somehow weird', group: 'Kommentare', risk: 'ok', say: 'irgendwie' },
      { de: 'lg / vg', en: 'kind regards (sign-off, also in DMs)', lit: 'liebe Grüße / viele Grüße', use: 'Danke, lg', useEn: 'Thanks, best', group: 'Kommentare', risk: 'ok', say: 'liebe Grüße' },
      { de: 'Abo', en: 'subscription / follow', lit: 'Abonnement', use: 'Abo dagelassen!', useEn: 'Subscribed!', group: 'Kommentare', risk: 'ok' },
      { de: 'Teil 2 bitte', en: 'part 2 please — the single most common German comment', lit: 'part 2 please',
        use: 'Teil 2 bitte!!', useEn: 'Part 2 please!!', group: 'Kommentare', risk: 'ok' },
      { de: 'wer ist auch 2026 hier?', en: "who's also here in 2026?", lit: 'who is also 2026 here',
        use: 'wer ist auch 2026 hier? 🙋', useEn: "who's here in 2026?", group: 'Kommentare', risk: 'ok' },
      { de: 'Der Algorithmus hat mich hergebracht', en: 'the algorithm brought me here', lit: 'same',
        use: 'Der Algorithmus hat mich hergebracht.', useEn: 'The algorithm brought me here.', group: 'Kommentare', risk: 'ok' },

      /* -------------------------------------------------- Gesprochen ---
         Spoken German eats its endings. This is the #1 reason a beginner
         can read German fine but understand nothing in a video.          */
      { de: 'Haste?', en: 'do you have?', lit: 'Hast du → Haste', use: 'Haste mal Feuer?', useEn: 'Got a light?', group: 'Gesprochen', risk: 'ok' },
      { de: 'Biste?', en: 'are you?', lit: 'Bist du → Biste', use: 'Biste schon da?', useEn: 'You there yet?', group: 'Gesprochen', risk: 'ok' },
      { de: 'Kannste', en: 'can you', lit: 'Kannst du → Kannste', use: 'Kannste mal helfen?', useEn: 'Can you help?', group: 'Gesprochen', risk: 'ok' },
      { de: 'Ich hab / ich geh', en: 'habe and gehe lose their -e in speech, always', lit: 'ich habe → ich hab',
        use: 'Ich hab kein Bock, ich geh nach Hause.', useEn: "I don't feel like it, I'm going home.", group: 'Gesprochen', risk: 'ok' },
      { de: '…, ne?', en: 'right? — tacked onto the end of half of all sentences', lit: 'nicht wahr',
        use: 'Ist kalt heute, ne?', useEn: "It's cold today, right?", group: 'Gesprochen', risk: 'ok' },
      { de: '…, oder?', en: 'or…? — same job as "ne?", slightly softer', lit: 'or',
        use: 'Wir sagen um acht, oder?', useEn: "We're saying eight, right?", group: 'Gesprochen', risk: 'ok' },
      { de: 'nix', en: 'nothing (spoken form of nichts)', lit: 'nichts', use: 'Ich hab nix gehört.', useEn: "I heard nothing.", group: 'Gesprochen', risk: 'ok' },
      { de: 'ganz', en: 'quite / very — meaning flips with tone', lit: 'whole',
        use: 'Das war ganz gut.', useEn: '"Pretty good" or "just OK" — listen to the tone.', group: 'Gesprochen', risk: 'ok' },
      { de: 'so (als Pause)', en: 'like — the German filler, same as English "like"', lit: 'so',
        use: 'Und ich so: was?!', useEn: 'And I was like: what?!', group: 'Gesprochen', risk: 'ok' },
      { de: 'Und ich so… und er so…', en: 'narrating a story in quotes: "and I was like…"', lit: 'and I so',
        use: 'Und ich so: nein. Und er so: doch.', useEn: 'And I was like: no. And he was like: yes.', group: 'Gesprochen', risk: 'ok' },
      { de: 'gucken', en: 'to look/watch — far more common in speech than "schauen" up north', lit: 'to look',
        use: 'Guck mal!', useEn: 'Look!', group: 'Gesprochen', risk: 'ok' },

      /* -------------------------------------------------- Füllwörter ---
         Modal particles: they carry attitude, not meaning. Leave them out
         and your German is correct but weirdly flat.                     */
      { de: 'mal', en: 'softens a command into a friendly ask', lit: 'once',
        use: 'Komm mal her.', useEn: 'Come here (friendly, not barked).', group: 'Füllwörter', risk: 'ok' },
      { de: 'doch', en: 'yes-it-is! Contradicts a negative. Also adds urgency', lit: '—',
        use: 'Du kommst nicht. — Doch!', useEn: "You're not coming. — Yes I am!", group: 'Füllwörter', risk: 'ok' },
      { de: 'halt / eben', en: '"just… that\'s how it is" — resignation', lit: '—',
        use: 'Das ist halt so.', useEn: "That's just how it is.", group: 'Füllwörter', risk: 'ok' },
      { de: 'ja', en: 'as a particle: "as you know / obviously"', lit: 'yes',
        use: 'Das ist ja klar.', useEn: "That's obvious, isn't it.", group: 'Füllwörter', risk: 'ok' },
      { de: 'denn', en: 'makes a question sound curious instead of like an interrogation', lit: '—',
        use: 'Was machst du denn?', useEn: 'So what are you up to?', group: 'Füllwörter', risk: 'ok' },
      { de: 'eigentlich', en: 'actually / to be honest', lit: 'actually',
        use: 'Eigentlich wollte ich schlafen.', useEn: 'I actually wanted to sleep.', group: 'Füllwörter', risk: 'ok' },
      { de: 'schon', en: 'already — as a particle: "sure, but…"', lit: 'already',
        use: 'Das schon, aber…', useEn: 'Sure, but…', group: 'Füllwörter', risk: 'ok' },
      { de: 'echt', en: 'really — the everyday intensifier', lit: 'genuine',
        use: 'Das ist echt gut.', useEn: "That's really good.", group: 'Füllwörter', risk: 'ok' }
    ]
  };
})();
